using System;
using System.IO;
using System.Numerics;

namespace LithophaneGenerator
{
    public class StlExporter : IStlExporter
    {
        private const string Author = "Author: YourName";
        private const string Software = "Software: YourSoftware";
        private const string Description = "Description: Generated by STLExporter";

        public void SaveAsSTL(double[,] heightMap, int finalWidthMM, int finalHeightMM, string filename, int resolution)
        {
            int width = heightMap.GetLength(1);
            int height = heightMap.GetLength(0);
            double scaleX = (double)finalWidthMM / width;
            double scaleY = (double)finalHeightMM / height;

            try
            {
                using (BinaryWriter writer = new BinaryWriter(File.Open(filename, FileMode.Create)))
                {
                    string header = CreateHeader();
                    writer.Write(System.Text.Encoding.ASCII.GetBytes(header.PadRight(80)));
                    int numTriangles = (width - 1) * (height - 1) * 2;
                    writer.Write(numTriangles);

                    for (int y = 0; y < height - 1; y++)
                    {
                        for (int x = 0; x < width - 1; x++)
                        {
                            var v0 = new Vector3((float)(x * scaleX), (float)(y * scaleY), (float)heightMap[y, x]);
                            var v1 = new Vector3((float)((x + 1) * scaleX), (float)(y * scaleY), (float)heightMap[y, x + 1]);
                            var v2 = new Vector3((float)(x * scaleX), (float)((y + 1) * scaleY), (float)heightMap[y + 1, x]);
                            var v3 = new Vector3((float)((x + 1) * scaleX), (float)((y + 1) * scaleY), (float)heightMap[y + 1, x + 1]);

                            WriteTriangle(writer, v0, v1, v2);
                            WriteTriangle(writer, v1, v3, v2);
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                throw new Exception($"Chyba při ukládání STL souboru: {ex.Message}");
            }
        }

        private void WriteTriangle(BinaryWriter writer, Vector3 v0, Vector3 v1, Vector3 v2)
        {
            var normal = Vector3.Cross(v1 - v0, v2 - v0);
            normal = Vector3.Normalize(normal);

            writer.Write(normal.X);
            writer.Write(normal.Y);
            writer.Write(normal.Z);

            writer.Write(v0.X);
            writer.Write(v0.Y);
            writer.Write(v0.Z);
            writer.Write(v1.X);
            writer.Write(v1.Y);
            writer.Write(v1.Z);
            writer.Write(v2.X);
            writer.Write(v2.Y);
            writer.Write(v2.Z);

            writer.Write((ushort)0);
        }

        private string CreateHeader()
        {
            string header = $"{Author}; {Software}; {Description}";
            return header;
        }
    }
}
